version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/Presensi?replicaSet=rs0
      - AUTH_SECRET=${AUTH_SECRET:-nrehivnajrnauirgnuoaeaovnraviyerbvain}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:5010}
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      mongo_setup:
        condition: service_completed_successfully

  mongo:
    image: mongo:6
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "5110:27017"
    volumes:
      - mongo_data:/data/db

  mongo_setup:
    image: mongo:6
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    command: ["bash", "/scripts/setup.sh"]

volumes:
  mongo_data:
  uploads_data:
