services:
  mongo:
    image: mongo:6
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "5110:27017"
    volumes:
      - mongo_data_v2:/data/db
    networks:
      - app-net
    restart: unless-stopped

  mongo-init:
    image: mongo:6
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - app-net
    entrypoint: ["mongosh", "--host", "mongo", "--eval", "try{rs.status()}catch(e){rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]})}"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/Presensi?replicaSet=rs0&directConnection=true
      - AUTH_SECRET=${AUTH_SECRET:-nrehivnajrnauirgnuoaeaovnraviyerbvain}
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://100.69.98.9:5010}
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      - mongo
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  mongo_data_v2:
  uploads_data:
